---
title: "Descriptive characteristics of Long COVID Cohorts"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      warning=FALSE, 
                      message=FALSE, 
                      comment = FALSE,
                      cache.lazy=FALSE)
options(scipen=999)

```


```{r include=FALSE}
# packages
library(SqlRender)
library(DBI)
library(DatabaseConnector)
library(here)
library(dplyr)
library(tidyr)
library(CDMConnector)
library(stringr)
library(lubridate)
library(gtsummary)
library(tableone)
library(kableExtra)

# Connection details ----
server    <- Sys.getenv("SERVER_JUN22")
server_dbi<- Sys.getenv("SERVER_DBI_JUN22")
user      <- Sys.getenv("DB_USER_JUN22")
password  <- Sys.getenv("DB_PASSWORD_JUN22")
port      <- Sys.getenv("DB_PORT_JUN22") 
host      <- Sys.getenv("DB_HOST_JUN22") 


db <- dbConnect(RPostgres::Postgres(), 
                dbname = server_dbi,
                port = port,
                host = host, 
                user = user, 
                password = password)

targetDialect              <- "postgresql"
cdm_database_schema        <- "omop21t4_cmbd" 
vocabulary_database_schema <-"omop21t4_cmbd" 
write_schema               <-"results21t4_cmbd"

# Generate cdm object to access the tables
cdm <- cdm_from_con(db, 
             cdm_schema = cdm_database_schema,
             write_schema = write_schema,
             cohort_tables = c("er_long_covid_final_cohorts",
                               "er_long_covid_all_symptoms_cohorts"))

#  get ids for cohorts

cohorts_ids  <- read.csv2(here("ATLAS Cohort Definitions_LongCovid.csv")) %>%
                          mutate(name= paste(sub(".*LongCov-ER_", "", name)))

new_infection_id <- as.character(cohorts_ids %>%
                    filter(str_detect(name, "New_Infection")) %>% 
                    select(cohort_definition_id) %>% pull())

tested_positive_id <- as.character(cohorts_ids %>%
                    filter(str_detect(name, "Tested_Positive")) %>% 
                    select(cohort_definition_id) %>% pull())

tested_negative_earliest_id <- as.character(cohorts_ids %>%
                    filter(str_detect(name, "Tested_Negative_earliest")) %>% 
                    select(cohort_definition_id) %>% pull())

pcr_negative_earliest_id <-as.character( cohorts_ids %>%
                    filter(str_detect(name, "PCR_Negative_earliest")) %>% 
                    select(cohort_definition_id) %>% pull())

# get data for table 1
load(here("data", "table1_data.Rdata"))


```



```{r include=FALSE}
table1.data<-rbind(  
# those without missing values
       table1_data_new_infections   %>%
        mutate(group = "COVID-19_infection"),
        table1_data_new_infections  %>%
        filter(long_covid == 1)%>%
          mutate(group = "Long Covid symptoms (90 days)"))


# variables
vars<-c(
        "age",
        "age_gr2",
        "gender",
        "trimester",
        "nationality_cat",
        "vaccination_status",
        "medea",
        "asthma",
        "autoimmune_disease",
        "copd",
        "dementia",
        "diabetes",
        "heart_disease",
        "cancer",
        "hypertension",
        "renal_impairment"
)

factor.vars<- c(
        "age_gr2",
        "gender",
                "trimester",
        "nationality_cat",
        "vaccination_status",
        "medea",
        "asthma",
        "autoimmune_disease",
        "copd",
        "dementia",
        "diabetes",
        "heart_disease",
        "cancer",
        "hypertension",
        "renal_impairment"
)



summary.characteristics<-print(CreateTableOne(
  vars =  vars,
  factorVars = factor.vars,
  includeNA=T,
  data = table1.data,
  strata=c("group"),
  test = F), 
  showAllLevels=F,
  smd=T,
  nonnormal = vars, #all 
  noSpaces = TRUE,
  contDigits = 1,
  printToggle=FALSE)


 
```



## Table: Baseline characteristics of individuals with COVID-19 and with long COVID-19 
```{r}

kable(summary.characteristics, 
      col.names = c("New COVID-19 infection",  
                    "Long COVID-19, 90 days",
                    "SMD"
                    ))%>%
  kable_styling(bootstrap_options = c("striped", "bordered")) #%>%
 # pack_rows("Baseline comorbidities", 40, 44)


```




```{r include=FALSE}
table2.data<-rbind(  
# those without missing values
       table1_data_tested_negative   %>%
        mutate(group = "1- Tested negative"),
       table1_data_tested_negative   %>%
        filter(long_covid == 1)%>%
          mutate(group = "2- Long Covid symptoms (90 days)"))


# variables
vars<-c(
        "age",
        "age_gr2",
        "gender",
        "trimester",
        "nationality_cat",
        "vaccination_status",
        "medea",
        "asthma",
        "autoimmune_disease",
        "copd",
        "dementia",
        "diabetes",
        "heart_disease",
        "cancer",
        "hypertension",
        "renal_impairment"
)

factor.vars<- c(
        "age_gr2",
        "gender",
                "trimester",
        "nationality_cat",
        "vaccination_status",
        "medea",
        "asthma",
        "autoimmune_disease",
        "copd",
        "dementia",
        "diabetes",
        "heart_disease",
        "cancer",
        "hypertension",
        "renal_impairment"
)



summary.characteristics.negative <-print(CreateTableOne(
  vars =  vars,
  factorVars = factor.vars,
  includeNA=T,
  data = table2.data,
  strata=c("group"),
  test = F), 
  showAllLevels=F,
  smd=T,
  nonnormal = vars, #all 
  noSpaces = TRUE,
  contDigits = 1,
  printToggle=FALSE)


 
```


## Table: Baseline characteristics of individuals tested negative and with long COVID-18 symptoms
```{r}

kable(summary.characteristics.negative, 
      col.names = c("Tested negative, earliest",  
                    "Long COVID-19 symptoms, 90 days",
                    "SMD"
                    ))%>%
  kable_styling(bootstrap_options = c("striped", "bordered")) #%>%
 # pack_rows("Baseline comorbidities", 40, 44)


```



```{r include=FALSE}
table3.data<-rbind(  
# those without missing values
        table1_data_new_infections  %>%
        mutate(group = "New infections"),
        table1_data_tested_negative   %>%
        mutate(group = "Tested negative"))


# variables
vars<-c(
        "age",
        "age_gr2",
        "gender",
        "trimester",
        "nationality_cat",
        "vaccination_status",
        "medea",
        "asthma",
        "autoimmune_disease",
        "copd",
        "dementia",
        "diabetes",
        "heart_disease",
        "cancer",
        "hypertension",
        "renal_impairment",
                "long_covid"

)

factor.vars<- c(
        "age_gr2",
        "gender",
                "trimester",
        "nationality_cat",
        "vaccination_status",
        "medea",
        "asthma",
        "autoimmune_disease",
        "copd",
        "dementia",
        "diabetes",
        "heart_disease",
        "cancer",
        "hypertension",
        "renal_impairment",
        "long_covid"
)



summary.characteristics.infection.negative <-print(CreateTableOne(
  vars =  vars,
  factorVars = factor.vars,
  includeNA=T,
  data = table3.data,
  strata=c("group"),
  test = F), 
  showAllLevels=F,
  smd=T,
  nonnormal = vars, #all 
  noSpaces = TRUE,
  contDigits = 1,
  printToggle=FALSE)


 
```


## Table: Baseline characteristics of individuals tested negative and with long COVID-18 symptoms
```{r}

kable(summary.characteristics.infection.negative, 
      col.names = c("New COVID-19 infection",  
                    "Tested negative",
                    "SMD"
                    ))%>%
  kable_styling(bootstrap_options = c("striped", "bordered")) #%>%
 # pack_rows("Baseline comorbidities", 40, 44)


```









```{r include=FALSE}
# function to obtain data for table
generate_table <- function(cohort_id, window, name){
data <- cdm$er_long_covid_all_symptoms_cohorts %>%
  filter(main_cohort_id == cohort_id & window_days == window) %>%
  distinct() %>%
  collect()
summary <-  data%>% 
  mutate(all_symp = as.factor(all_symp)) %>%
  select(-subject_id, -window_days, - main_cohort_id, - cohort_start_date ) %>%
  mutate(gen = paste0(name)) %>%
   tbl_summary(
       by = "gen",
  digits = all_categorical()~ c(0,1),
  missing = "ifany",
  missing_text= "Missing",
  percent = "col"
           ) %>% 
  bold_labels()
  summary
}
```



```{r include=FALSE}
t.covid.infection <- generate_table(cohort_id= new_infection_id,
                                    window="90",
                                    name = "New COVID-19 infection")

t.covid.confirmed <- generate_table(cohort_id= tested_positive_id,
                                    window="90",
                                    name = "Confirmed infections")

t.covid.reinfections <- generate_table(cohort_id= "71",
                                    window="90",
                                    name = "Reinfections")


t.tested.negative.earliest <- generate_table(cohort_id = tested_negative_earliest_id,
                                    window="90",
                                    name = "Tested negative, earliest")

t.pcr.negative.earliest <- generate_table(cohort_id = pcr_negative_earliest_id,
                                    window="90",
                                    name = "PCR negative, earliest")




```

## Table: Symptoms distribution across cohorts

```{r}
table  <- tbl_merge(tbls = list(t.covid.infection,   
                                t.covid.confirmed,
                                t.covid.reinfections,
                                t.tested.negative.earliest,
                                t.pcr.negative.earliest
                                 ), 
                     tab_spanner = c("","", "", "", ""))

table

```

